FROM ubuntu

ENV DB_HOST localhost
ENV MAILGUN_ACCESS_KEY 12345
ENV MAILGUN_SERVER_NAME localhost
ENV SENTRY_URL_PREFIX http://sentry.local.com
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# update packages (cachebust)
RUN apt-get update && apt-get upgrade -y

# we want python (and pip)
RUN apt-get install -y \
	build-essential \
	language-pack-en \
	python-dev \
	python-pip \
	postgresql \
	postgresql-contrib \
	libpq-dev

# set locales (for postgres)
RUN locale-gen en_US.UTF-8

# add the source code
RUN mkdir -p /app
WORKDIR /app
ADD . /app/

# install sentry and postgres binding
RUN pip install -r requirements.txt

# move sentry config to default location
ADD sentry.conf.py ~/.sentry/sentry.conf.py

EXPOSE 9000

#FROMCACHE vida-sentry
